#!/usr/bin/env bash
#
#
VERSION="1.0.1"
sudo cp autohotspot/*.sh /usr/local/bin/
sudo cp autohotspot/autohotspot.desktop /usr/local/share/applications/
[ -f $HOME/.local/share/applications/autohotspot.desktop ] && rm -f $HOME/.local/share/applications/autohotspot.desktop
